### ISSUE TITLE
[BUG] BigQuery syntax error when running "dbt run --models package:re_data"

### ISSUE THREAD

**Issue by casperhansen** [re-data/dbt-re-data#12]
**Describe the bug**
I run this:
`dbt run --models package:re_data --vars \
   '{
     "re_data:time_window_start": "2021-01-01 00:00:00",
     "re_data:time_window_end": "2021-01-02 00:00:00"
    }'
`
using a BigQuery DB. 
I can the following error message:
`
16:01:26 | 3 of 18 ERROR creating incremental model dbt_chansen_re.re_data_base_metrics [ERROR in 31.59s]
Database Error in model re_data_base_metrics (models/intermediate/re_data_base_metrics.sql)
  Syntax error: Expected ")" but got ":" at [330:21]
  compiled SQL at target/run/re_data/models/intermediate/re_data_base_metrics.sql
`

Line 315-345 of is pasted below (the code highlight does not work well on it due to the use of the "`" in the SQL):

as computed_on
             union all
            select 
                '`dbt_chansen`.`active_periods`' as table_name,
                'user_id' as column_name,
                'min' as metric,
                null::integer as value,
    cast('2021-01-02 00:00:00' as timestamp) 
as time_window_start,
    cast('2021-01-03 00:00:00' as timestamp)
as time_window_end,
    current_timestamp
as computed_on union all   # <---- this is line 330
            select 
                '`dbt_chansen`.`active_periods`' as table_name,
                'user_id' as column_name,
                'max' as metric,
                null::integer as value,
    cast('2021-01-02 00:00:00' as timestamp) 
as time_window_start,
    cast('2021-01-03 00:00:00' as timestamp)
as time_window_end,
    current_timestamp
as computed_on union all

**To Reproduce**
I am unable to provide this due to proprietary data.

**Comment by mateuszklimek** [comment]
Resolved :)
